### ISSUE TITLE
Use relevant HTTP codes for errors

### ISSUE THREAD

**Issue by mnazbro** [palantir/typedjsonrpc#70]
We should probably be returning error codes whenever we return a message which is invalid. The JSON-RPC specification doesn't have any particular codes which should be used, so we can choose ones which are appropriate. Currently, I'm thinking:

Normal responses: 200
Empty responses (notifications): 204
ParseError, InvalidRequestError: 400
MethodNotFoundError: 404
Everything else: 500

**Comment by punya** [comment]
What happens when I submit a batch of 2 requests and only one of them fails (or more generally, when there's heterogeneous status)?

**Comment by mnazbro** [comment]
I'm thinking that if you have a batch you can do this:
Batch of all notifications: 204
Batch with no notifications: 200

The main reason for this is that there is no way to mix up return codes, so we might as well give up and respond with a 200. If the user is batching, they must understand that there may be some failed things in the batch.

**Comment by punya** [comment]
Cool, so is the proposal:
* if all calls are notifications, status = 204
* if there's only one call, status = appropriate indicator
* otherwise, status = 200

**Comment by mnazbro** [comment]
Yes, that's the proposal

**Comment by punya** [comment]
:+1:

**Comment by mmmarklu** [comment]
Can we also include a relevant reason phrase with the status code? It should be the same as the error in the response body.

for example:

404 Could not find method 'palantir.example'
